global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'VIABLE Credentials-Monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'viable-credentials'
    scheme: 'https'
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['root.85-215-156-198.sslip.io']
    metrics_path: '/metrics'
    scrape_interval: 10s
