global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'StudentVC-Monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'studentvc'
    scheme: 'https'
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['172.26.21.41:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s
